### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by evgerher** [evgerher/TRPO#1]
Задание выполнил
Сорокин Евгений
@evgeny-p

**Comment by evgeny-p** [comment]
Удаление репозитория со всеми комментариями определенно было лишним. Не осталось истории: какие были замечания. Сложно оценить изменения и приходится проверять все заново.

Не исправлено одно замечание из прошлого репозитория: коэффициенты `a`, `b`, `c` почему-то типа `int`, хотя по факту они могут быть числами с плавающей точкой.

Работа принята, задачу можно закрывать.
